apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-registration-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
