apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  application.yml: |
    server:
      port: 8080
    spring:
      application:
        name: gateway
      cloud:
        gateway:
          routes:
            - id: route-consumer
              uri: http://consumer:8080
              predicates:
                - Path=/consumer/**
              filters:
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: route-producer
              uri: http://producer:8080
              predicates:
                - Path=/producer/**
              filters:
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: route-security
              uri: http://security:8080
              predicates:
                - Path=/security/**
              filters:
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

            - id: route-registration
              uri: http://registration:8080
              predicates:
                - Path=/registration/**
              filters:
                - PreserveHostHeader
                - RemoveRequestHeader=Cookie

    logging:
      level:
        root: DEBUG
