apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      automountServiceAccountToken: false
      containers:
        - name: producer
          image: hackaton-producer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/hackaton"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "756Mi"
          volumeMounts:
            - name: input-volume
              mountPath: /input
            - name: output-volume
              mountPath: /output
      volumes:
        - name: input-volume
          hostPath:
            path: /data/input
            type: DirectoryOrCreate
        - name: output-volume
          hostPath:
            path: /data/output
            type: DirectoryOrCreate